### ISSUE TITLE
Работа с категориями тестов

### ISSUE THREAD

**Issue by olegbolden** [geektesting/testing#13]
Создать класс для работы с категориями: просмотр списка, создание, удаление, перемещение.

Для категорий тестов приняты следующие положения:

1. Администратор создаёт рубрикатор из общедоступных категорий тестов.
2. Пользователи могут публиковать там свои тесты, но не могут создавать подкатегории.
3. Пользователи могут создавать подкатегории в какой-то отдельной папке типа «Частные 
категории», которая также растёт из корня рубрикатора, созданного администратором.

В итоге структура рубрикатора такова:

Программирование->JavaScript->тесты
...
Частные категории->(GeekBrains->)… своя иерархия …->тесты

**Comment by PeresvetS** [comment]
Closed #21
