### ISSUE TITLE
Создать меню выбора категорий с тестами

### ISSUE THREAD

**Issue by olegbolden** [geektesting/testing#24]
На основной странице сайта необходимо сделать меню с подпунктами, совпадающими с уровнями иерархии категорий тестов.
1) Основными пунктами меню являются пункты нулевого уровня.
2) Кликабельными сделать только концевые категории (категории без дочерних категорий). По необходимости потом сделаем кликабельными и промежуточные.

**Comment by PeresvetS** [comment]
Closed #52
