### ISSUE TITLE
Работа с тестами

### ISSUE THREAD

**Issue by PeresvetS** [geektesting/testing#32]
- [x] Создать в БД таблицу, где будут храниться названия тестов.
- [x] Создать класс для просмотра, создания, редактирования и удаления тестов.
- [x] Отобразить всё на сайте.

**Comment by olegbolden** [comment]
До конца недели постараюсь создать класс для просмотра, создания, редактирования и удаления тестов, а также отобразить всё это на сайте.

**Comment by PeresvetS** [comment]
Closed #46 #47
