### ISSUE TITLE
Страница авторизации, регистрации

### ISSUE THREAD

**Issue by PeresvetS** [geektesting/testing#45]
Создать приятну вёрстку для страниц авторизации и регистрации.

**Comment by roman2211** [comment]
[geektest avt.zip](https://github.com/geektesting/testing/files/1346414/geektest.avt.zip)
верстка страницы авторизации

**Comment by roman2211** [comment]
[geektest avt.zip](https://github.com/geektesting/testing/files/1346441/geektest.avt.zip)
верстка страницы авторизации

**Comment by roman2211** [comment]
[geekreg.zip](https://github.com/geektesting/testing/files/1346936/geekreg.zip)

верстка страницы регистрации

**Comment by roman2211** [comment]
[geekreg.zip](https://github.com/geektesting/testing/files/1349715/geekreg.zip)
[geektest avt.zip](https://github.com/geektesting/testing/files/1349714/geektest.avt.zip)

верстка авторизации и регистрации

**Comment by PeresvetS** [comment]
Closed #48
